### ISSUE TITLE
Client/Manager Release 8.0.2 is available

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/edu.berkeley.BOINC#17]
Client/Manager Release 8.0.2 is available

https://github.com/BOINC/boinc/releases/tag/client_release%2F8.0%2F8.0.2

**Comment by sohrob** [comment]
Will there no longer be a Flatpak edition of BOINC?

**Comment by hendkai** [comment]
I would like to contribute with my gaming pc but there is no latest versin available. Its important for imutable systems like bazzite etc....

**Comment by AenBleidd** [comment]
New version is built and published
