### ISSUE TITLE
Skins folder is not included in the package

### ISSUE THREAD

**Issue by AenBleidd** [flathub/edu.berkeley.BOINC#6]
After they are included in the package, BOINC upstream should provide a fix to search for a proper skins folder location

**Comment by idunno101** [comment]
The skins show up in the Manager now after implementing #8.
The root directory for the Flatpak application is /app/ so I added that condition to the SkinManager.cpp file for now.

Users are also able to create their own skins, right? It would be good to also search in the app's home directory for skins that the user added alongside the prepackaged skins in /app/share

Is the SkinManager able to pull in skins from two different locations and list them all together in the GUI?

**Comment by AenBleidd** [comment]
> Is the SkinManager able to pull in skins from two different locations and list them all together in the GUI?

No, but this might be a good feature. Thank you for the fix!
Meanwhile you can push your change upstream and create a PR if you want
